
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.688-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "cancelMessages_com.sap.aii.mdt.server.adapterframework.ws.InvalidKeyException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class CancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.InvalidKeyException cancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException;

    public CancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc() {
        super();
    }
    
    public CancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc(String message) {
        super(message);
    }
    
    public CancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public CancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc(String message, com.ulta.monitoring.pimonitoring.InvalidKeyException cancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException) {
        super(message);
        this.cancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException = cancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException;
    }

    public CancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc(String message, com.ulta.monitoring.pimonitoring.InvalidKeyException cancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException, Throwable cause) {
        super(message, cause);
        this.cancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException = cancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException;
    }

    public com.ulta.monitoring.pimonitoring.InvalidKeyException getFaultInfo() {
        return this.cancelMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException;
    }
}
