
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.683-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "cancelMessages_com.sap.aii.mdt.server.adapterframework.ws.OperationFailedException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class CancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.OperationFailedException cancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;

    public CancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc() {
        super();
    }
    
    public CancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message) {
        super(message);
    }
    
    public CancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public CancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException cancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException) {
        super(message);
        this.cancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException = cancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public CancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException cancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException, Throwable cause) {
        super(message, cause);
        this.cancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException = cancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public com.ulta.monitoring.pimonitoring.OperationFailedException getFaultInfo() {
        return this.cancelMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }
}
