
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.773-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "getAllAvailableStatusDetails_com.sap.aii.mdt.server.adapterframework.ws.OperationFailedException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class GetAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.OperationFailedException getAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;

    public GetAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc() {
        super();
    }
    
    public GetAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message) {
        super(message);
    }
    
    public GetAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException) {
        super(message);
        this.getAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public GetAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException, Throwable cause) {
        super(message, cause);
        this.getAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public com.ulta.monitoring.pimonitoring.OperationFailedException getFaultInfo() {
        return this.getAllAvailableStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }
}
