
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.759-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "getConnections_com.sap.aii.mdt.server.adapterframework.ws.OperationFailedException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class GetConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.OperationFailedException getConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;

    public GetConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc() {
        super();
    }
    
    public GetConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message) {
        super(message);
    }
    
    public GetConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public GetConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedException) {
        super(message);
        this.getConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public GetConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedException, Throwable cause) {
        super(message, cause);
        this.getConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public com.ulta.monitoring.pimonitoring.OperationFailedException getFaultInfo() {
        return this.getConnectionsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }
}
