
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.678-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "getErrorCodes_com.sap.aii.mdt.server.adapterframework.ws.OperationFailedException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class GetErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.OperationFailedException getErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;

    public GetErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc() {
        super();
    }
    
    public GetErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message) {
        super(message);
    }
    
    public GetErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public GetErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedException) {
        super(message);
        this.getErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public GetErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedException, Throwable cause) {
        super(message, cause);
        this.getErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public com.ulta.monitoring.pimonitoring.OperationFailedException getFaultInfo() {
        return this.getErrorCodesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }
}
