
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.722-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "getIntegrationFlows_com.sap.aii.mdt.server.adapterframework.ws.OperationFailedException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class GetIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.OperationFailedException getIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;

    public GetIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc() {
        super();
    }
    
    public GetIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message) {
        super(message);
    }
    
    public GetIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public GetIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedException) {
        super(message);
        this.getIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public GetIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedException, Throwable cause) {
        super(message, cause);
        this.getIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public com.ulta.monitoring.pimonitoring.OperationFailedException getFaultInfo() {
        return this.getIntegrationFlowsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }
}
