
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.713-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "getInterfaces_com.sap.aii.mdt.server.adapterframework.ws.OperationFailedException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class GetInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.OperationFailedException getInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;

    public GetInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc() {
        super();
    }
    
    public GetInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message) {
        super(message);
    }
    
    public GetInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public GetInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedException) {
        super(message);
        this.getInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public GetInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedException, Throwable cause) {
        super(message, cause);
        this.getInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public com.ulta.monitoring.pimonitoring.OperationFailedException getFaultInfo() {
        return this.getInterfacesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }
}
