
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.767-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "getLogEntries_com.sap.aii.mdt.server.adapterframework.ws.InvalidKeyException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class GetLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.InvalidKeyException getLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException;

    public GetLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc() {
        super();
    }
    
    public GetLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc(String message) {
        super(message);
    }
    
    public GetLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public GetLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc(String message, com.ulta.monitoring.pimonitoring.InvalidKeyException getLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException) {
        super(message);
        this.getLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException = getLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException;
    }

    public GetLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc(String message, com.ulta.monitoring.pimonitoring.InvalidKeyException getLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException, Throwable cause) {
        super(message, cause);
        this.getLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException = getLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException;
    }

    public com.ulta.monitoring.pimonitoring.InvalidKeyException getFaultInfo() {
        return this.getLogEntriesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException;
    }
}
