
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.779-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "getMessagesByKeys_com.sap.aii.mdt.server.adapterframework.ws.OperationFailedException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class GetMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.OperationFailedException getMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedException;

    public GetMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc() {
        super();
    }
    
    public GetMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message) {
        super(message);
    }
    
    public GetMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public GetMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedException) {
        super(message);
        this.getMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public GetMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedException, Throwable cause) {
        super(message, cause);
        this.getMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public com.ulta.monitoring.pimonitoring.OperationFailedException getFaultInfo() {
        return this.getMessagesByKeysComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }
}
