
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.727-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "getMessageList_com.sap.aii.mdt.server.adapterframework.ws.OperationFailedException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class GetMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.OperationFailedException getMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedException;

    public GetMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc() {
        super();
    }
    
    public GetMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message) {
        super(message);
    }
    
    public GetMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public GetMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedException) {
        super(message);
        this.getMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public GetMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedException, Throwable cause) {
        super(message, cause);
        this.getMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public com.ulta.monitoring.pimonitoring.OperationFailedException getFaultInfo() {
        return this.getMessageListComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }
}
