
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.709-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "getStatusDetails_com.sap.aii.mdt.server.adapterframework.ws.OperationFailedException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class GetStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.OperationFailedException getStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;

    public GetStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc() {
        super();
    }
    
    public GetStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message) {
        super(message);
    }
    
    public GetStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public GetStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException) {
        super(message);
        this.getStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public GetStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException, Throwable cause) {
        super(message, cause);
        this.getStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public com.ulta.monitoring.pimonitoring.OperationFailedException getFaultInfo() {
        return this.getStatusDetailsComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }
}
