
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.741-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "getUserDefinedSearchMessages_com.sap.aii.mdt.server.adapterframework.ws.OperationFailedException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class GetUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.OperationFailedException getUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;

    public GetUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc() {
        super();
    }
    
    public GetUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message) {
        super(message);
    }
    
    public GetUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public GetUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException) {
        super(message);
        this.getUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public GetUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException getUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException, Throwable cause) {
        super(message, cause);
        this.getUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException = getUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public com.ulta.monitoring.pimonitoring.OperationFailedException getFaultInfo() {
        return this.getUserDefinedSearchMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }
}
