
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.750-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "resendMessages_com.sap.aii.mdt.server.adapterframework.ws.InvalidKeyException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class ResendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.InvalidKeyException resendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException;

    public ResendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc() {
        super();
    }
    
    public ResendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc(String message) {
        super(message);
    }
    
    public ResendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public ResendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc(String message, com.ulta.monitoring.pimonitoring.InvalidKeyException resendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException) {
        super(message);
        this.resendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException = resendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException;
    }

    public ResendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyExceptionDoc(String message, com.ulta.monitoring.pimonitoring.InvalidKeyException resendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException, Throwable cause) {
        super(message, cause);
        this.resendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException = resendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException;
    }

    public com.ulta.monitoring.pimonitoring.InvalidKeyException getFaultInfo() {
        return this.resendMessagesComSapAiiMdtServerAdapterframeworkWsInvalidKeyException;
    }
}
