
package com.ulta.monitoring.pimonitoring;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-28T16:58:05.745-05:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "resendMessages_com.sap.aii.mdt.server.adapterframework.ws.OperationFailedException", targetNamespace = "urn:AdapterMessageMonitoringWsd/AdapterMessageMonitoringVi")
public class ResendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc extends Exception {
    
    private com.ulta.monitoring.pimonitoring.OperationFailedException resendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;

    public ResendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc() {
        super();
    }
    
    public ResendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message) {
        super(message);
    }
    
    public ResendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, Throwable cause) {
        super(message, cause);
    }

    public ResendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException resendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException) {
        super(message);
        this.resendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException = resendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public ResendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedExceptionDoc(String message, com.ulta.monitoring.pimonitoring.OperationFailedException resendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException, Throwable cause) {
        super(message, cause);
        this.resendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException = resendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }

    public com.ulta.monitoring.pimonitoring.OperationFailedException getFaultInfo() {
        return this.resendMessagesComSapAiiMdtServerAdapterframeworkWsOperationFailedException;
    }
}
